### ISSUE TITLE
New hook / script proposals

### ISSUE THREAD

**Issue by cmmata** [CompSciLauren/awesome-git-hooks#10] opened 2019-08-21 10:10 UTC
**Is your feature request related to a problem? Please describe.**
When people want to use git hooks to check something on the project, send notifications, or any kind of action, they have to know a bit of bash scripting or any other console language like python.

**Describe the solution you'd like**
It could be interesting to accept script proposals, like "I have a project X and would like to have a pre-commit script that lints every file commited with their respective linter". Then someone with enough knowledge (and time) could write that script and add it to the repo. Proposals could be Github issues for example, but it should be nice to add something like "if you don't find the script you want, you can ask for it in a new issue" in the Readme.

**Comment by CompSciLauren** [comment] 2019-08-22 03:41
Love the suggestion! I also agree with adding a friendly comment like that in the Readme. As for the Issue template, I've come up with a rough draft below. Please take a look and let me know what you think. :)

**Is your script request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe what you want the script to do.**
A clear description of what you want the script to do. Feel free to include pseudocode, a diagram, etc.

**Is there a specific language you would prefer the script to be written in?**
If no preference, please say so. Otherwise, list your preferred language and explain why you need it to be in that language.

**Do you have a project that would potentially use this script?**
Link to example project that might use this script. This could provide more insight for whoever writes the script.

**Anything else that would be helpful to know?**
If you want to add any additional details, please include them here.

**Comment by CompSciLauren** [comment] 2019-08-24 16:24
I've made the changes and they should be good to go, so I'm closing this Issue. That said, feel free to comment on this if you have anything to add and we can always revisit this if needed. Thanks!

**Closed by CompSciLauren** 2019-08-24 16:24 UTC
Labels: enhancement

**Comment by cmmata** [comment] 2019-08-26 16:19
I really like the link with the new proposal template! Good idea! Much better than the comment I was thinking about.

**Comment by cmmata** [comment] 2019-08-27 06:19
Well.. after all, GitHub is about collaboration 😊
